### ISSUE TITLE
Suggestion for a shorter day 1-1

### ISSUE THREAD

**Issue by vindarel** [aartaka/advent-of-code-in-cl-loop#1]
Hello,

Sorry to interrupt but I can't resist :p 

I think you can shorten day 1-1 by

- using `count`
- using `for … and … = … then …` and avoiding a `setf`
- avoiding setting a counter to 0

```lisp
(loop for depth in (measuments)
   and prev = nil then depth
   when prev
   count (< prev depth))
```

**Comment by aartaka** [comment]
Ha, indeed! That was not obvious when I was doing it! Thanks, I'll remember this trick and use it in the code ;)
